-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  bookmark_name text,
  title text, 
  url text, 
  description text, 
  rating INTEGER
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (bookmark_name, description, title, rating)
values
  ('Testing', 'bookmarks are great', 'title', 1),
  ('Bookmark1', 'Books are great 1', 'title2', 2),
  ('Bookmark2', 'Books are great 2', 'title3', 3),
  ('Bookmark3', 'Books are great 3', 'title4', 4),
  ('Bookmark4', 'Books are great 4', 'title5', 5),
  ('Bookmark5', 'Books are great 5', 'title6', 6),
  ('Bookmark6', 'Books are great 6', 'title7', 7),
  ('Bookmark7', 'Books are great 7', 'title8', 8),
  ('Bookmark8', 'Books are great 8', 'title9', 9),
  ('Bookmark9', 'Books are great 9', 'title10', 10);